version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: rapidphotoflow-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rapidphotodb
    volumes:
      - mongodb_data:/data/db
    networks:
      - rapidphotoflow-network

volumes:
  mongodb_data:
    driver: local

networks:
  rapidphotoflow-network:
    driver: bridge

